In [ ]:
from google.colab import drive
drive.mount('/gdrive', force_remount=True)

Mounted at /gdrive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

In [ ]:
df=pd.read_csv('/gdrive/My Drive/DS_contest/datathree_Interpolation_2.csv')

In [ ]:
df = df.drop(['Unnamed: 0','Unnamed: 0.1'],axis=1)
df.head(3)

   No       Y_t     J_t  ...  normal  J_t_pred  Interpolated X_t
0   1  418395.0  2026.0  ...       1    2084.3        206.512833
1   1  352095.0  2018.0  ...       1    2084.3        174.477205
2   1  260865.0  1983.0  ...       1    2084.3        131.550681

[3 rows x 9 columns]

In [ ]:
df['X_t'] = df['Interpolated X_t']
df=df.drop('Interpolated X_t',axis=1)
df.head(3)

   No       Y_t     J_t  ID index  time         X_t  normal  J_t_pred
0   1  418395.0  2026.0         0     2  206.512833       1    2084.3
1   1  352095.0  2018.0         0     3  174.477205       1    2084.3
2   1  260865.0  1983.0         0     4  131.550681       1    2084.3

In [ ]:
datathree=[]
datathree.append(df.loc[:,'X_t'])
datathree.append(df.loc[:, 'J_t_pred'])
datathree.append(df.loc[:, 'J_t'])
datathree.append(df.loc[:,'time'])
datathree.append(df.loc[:,'ID index'])

In [ ]:
dfthree=pd.DataFrame(datathree)
dfthree=dfthree.transpose()
dfthreetest=dfthree.copy()
dfthreetest

             X_t  J_t_pred     J_t  time  ID index
0     206.512833  2084.300  2026.0   2.0       0.0
1     174.477205  2084.300  2018.0   3.0       0.0
2     131.550681  2084.300  1983.0   4.0       0.0
3     104.656351  2084.300  2165.0   5.0       0.0
4      88.205092  2084.300  2121.0   6.0       0.0
...          ...       ...     ...   ...       ...
2779   39.396040  1906.875  2121.0  21.0     231.0
2780   42.604805  1906.875  2123.0  22.0     231.0
2781   39.117378  1906.875  1968.0  23.0     231.0
2782   26.692486  1906.875  2156.0  24.0     231.0
2783   22.609551  1906.875  2136.0  25.0     231.0

[2784 rows x 5 columns]

In [ ]:
for i in range (232):
  dfthreetest.drop([12*i+10], axis=0, inplace=True)
  dfthreetest.drop([12*i+11], axis=0, inplace=True)

In [ ]:
datathree_=[]
datathreetest_=[]
for i in range(232):
  datathree_.append(dfthree[dfthree['ID index']==i])
  datathreetest_.append(dfthreetest[dfthreetest['ID index']==i])

In [ ]:
def sMAPE(actual_values, predicted_values, expsMAPE = False):
  '''
  logY를 regression하는 경우에 expsMAPE = True로 입력, 아니면 expsMAPE = False로 놔두면 됨
  reg_sMAPE = GridSearchCV(RandomForestRegressor(), {}, scoring=make_scorer(sMAPE, greater_is_better=False)) 이런식으로 쓰면됨
  reg_sMAPE.fit(x,y)
  '''
  if expsMAPE == True:
    predicted_values = np.exp(predicted_values)
    actual_values = np.exp(actual_values)
  return 1/len(actual_values) * np.sum(2*np.abs(actual_values - predicted_values) / (np.abs(actual_values) + np.abs(predicted_values)) * 100)

Average로 해보기

일단 최근 (2, 3, 4)개 average로 (곱하기 상수)

In [ ]:
df = pd.read_csv('/gdrive/My Drive/DS_contest/datathree_Interpolation_2.csv')

In [ ]:
df['X_t'] = df['Interpolated X_t']
df = df.drop(['Unnamed: 0','Unnamed: 0.1', 'Interpolated X_t', 'normal', 'time', 'J_t'],axis=1)
df

       No       Y_t  ID index         X_t  J_t_pred
0       1  418395.0         0  206.512833  2084.300
1       1  352095.0         0  174.477205  2084.300
2       1  260865.0         0  131.550681  2084.300
3       1  226581.0         0  104.656351  2084.300
4       1  187083.0         0   88.205092  2084.300
...   ...       ...       ...         ...       ...
2779  722   83559.0       231   39.396040  1906.875
2780  722   90450.0       231   42.604805  1906.875
2781  722   76983.0       231   39.117378  1906.875
2782  722   57549.0       231   26.692486  1906.875
2783  722   48294.0       231   22.609551  1906.875

[2784 rows x 5 columns]

In [ ]:
data2 = []
for i in range(232):
  data2.append(df.iloc[12*i:12*i+12])
data2[0]

    No       Y_t  ID index         X_t  J_t_pred
0    1  418395.0         0  206.512833    2084.3
1    1  352095.0         0  174.477205    2084.3
2    1  260865.0         0  131.550681    2084.3
3    1  226581.0         0  104.656351    2084.3
4    1  187083.0         0   88.205092    2084.3
5    1  171573.0         0   84.145660    2084.3
6    1  158340.0         0   71.776972    2084.3
7    1  138864.0         0   63.062670    2084.3
8    1  128325.0         0   59.769446    2084.3
9    1  125439.0         0   64.792872    2084.3
10   1  135825.0         0   78.647944    2084.3
11   1  107850.0         0   49.269073    2084.3

In [ ]:
for i in range(232):
  data2[i] = data2[i].transpose()

In [ ]:
for i in range(232):
  data2[i].rename(columns = {12*i:0,12*i+1:1,12*i+2:2,12*i+3:3,12*i+4:4,12*i+5:5,12*i+6:6,12*i+7:7,12*i+8:8,12*i+9:9,12*i+10:10,12*i+11:11},inplace=True)
data2[1]

                     0              1   ...            10            11
No             3.000000       3.000000  ...      3.000000      3.000000
Y_t       388623.000000  385677.000000  ...  86910.000000  85182.000000
ID index       1.000000       1.000000  ...      1.000000      1.000000
X_t          282.224401     189.242885  ...     59.002037     38.931444
J_t_pred    2043.100000    2043.100000  ...   2043.100000   2043.100000

[5 rows x 12 columns]

In [ ]:
for i in range(232):
  data2[i] = data2[i].transpose()
data2[1]

     No       Y_t  ID index         X_t  J_t_pred
0   3.0  388623.0       1.0  282.224401    2043.1
1   3.0  385677.0       1.0  189.242885    2043.1
2   3.0  296070.0       1.0  143.932912    2043.1
3   3.0  235476.0       1.0  111.073585    2043.1
4   3.0  198243.0       1.0   92.897376    2043.1
5   3.0  170568.0       1.0   78.639004    2043.1
6   3.0  146442.0       1.0   69.502610    2043.1
7   3.0  126732.0       1.0   57.422746    2043.1
8   3.0  104511.0       1.0   48.836916    2043.1
9   3.0   97971.0       1.0   47.056196    2043.1
10  3.0   86910.0       1.0   59.002037    2043.1
11  3.0   85182.0       1.0   38.931444    2043.1

In [ ]:
y_test = []
y_pred_final = []
for i in range(232):
  y_test.append(data2[i]['Y_t'][10]+data2[i]['Y_t'][11])
  y_pred_final.append((0.4*data2[i]['X_t'][7]+data2[i]['X_t'][8]+8.2*data2[i]['X_t'][9])*data2[i]['J_t_pred'][0]*20/96 *0.89) #21.18

In [ ]:
df2 = data2[0]
for i in range(231):
  df2 = pd.concat([df2, data2[i+1]],axis=0,sort=False,join='inner')
df2

       No       Y_t  ID index  ...   Y_last3_pred   Y_last4_pred    Y_test
0     1.0  418395.0       0.0  ...  260711.174907  270335.752441  243675.0
1     1.0  352095.0       0.0  ...  260711.174907  270335.752441  243675.0
2     1.0  260865.0       0.0  ...  260711.174907  270335.752441  243675.0
3     1.0  226581.0       0.0  ...  260711.174907  270335.752441  243675.0
4     1.0  187083.0       0.0  ...  260711.174907  270335.752441  243675.0
..    ...       ...       ...  ...            ...            ...       ...
7   722.0   83559.0     231.0  ...  153971.539940  168371.157975  105843.0
8   722.0   90450.0     231.0  ...  153971.539940  168371.157975  105843.0
9   722.0   76983.0     231.0  ...  153971.539940  168371.157975  105843.0
10  722.0   57549.0     231.0  ...  153971.539940  168371.157975  105843.0
11  722.0   48294.0     231.0  ...  153971.539940  168371.157975  105843.0

[2784 rows x 12 columns]

In [ ]:
# 21.182 (0.4,1,8.2)
for i in range(50):
  print('sMAPE: ',sMAPE(np.array(y_test),np.array(y_weight1)*(1-0.005*i)),'index: ',i)

sMAPE:  24.386088277932302 index:  0
sMAPE:  24.13514989416595 index:  1
sMAPE:  23.885082415559783 index:  2
sMAPE:  23.644141620179635 index:  3
sMAPE:  23.405541167154595 index:  4
sMAPE:  23.1785513155473 index:  5
sMAPE:  22.966327528812048 index:  6
sMAPE:  22.755381372963953 index:  7
sMAPE:  22.553614088416495 index:  8
sMAPE:  22.37025338499575 index:  9
sMAPE:  22.200724712525535 index:  10
sMAPE:  22.044115665794006 index:  11
sMAPE:  21.9022729874515 index:  12
sMAPE:  21.77386321679228 index:  13
sMAPE:  21.659462493738555 index:  14
sMAPE:  21.5595902822747 index:  15
sMAPE:  21.473497483355224 index:  16
sMAPE:  21.398497199383858 index:  17
sMAPE:  21.329209311826204 index:  18
sMAPE:  21.275716378482354 index:  19
sMAPE:  21.229981259089985 index:  20
sMAPE:  21.19850775501135 index:  21
sMAPE:  21.182009662437828 index:  22
sMAPE:  21.201737313028527 index:  23
sMAPE:  21.246581526935106 index:  24
sMAPE:  21.29986551559886 index:  25
sMAPE:  21.37253184113361 index:  26
sMAPE:  21.450150668899983 index:  27
sMAPE:  21.54258638177802 index:  28
sMAPE:  21.64737498688313 index:  29
sMAPE:  21.75935714811882 index:  30
sMAPE:  21.886318491885103 index:  31
sMAPE:  22.02467945621045 index:  32
sMAPE:  22.181042502610957 index:  33
sMAPE:  22.36835422754282 index:  34
sMAPE:  22.576307093457576 index:  35
sMAPE:  22.801970388599496 index:  36
sMAPE:  23.031997609189563 index:  37
sMAPE:  23.269865395930953 index:  38
sMAPE:  23.519516168671903 index:  39
sMAPE:  23.77834726853178 index:  40
sMAPE:  24.04482162175549 index:  41
sMAPE:  24.317558527476727 index:  42
sMAPE:  24.59996976185343 index:  43
sMAPE:  24.88988924687935 index:  44
sMAPE:  25.191275461500652 index:  45
sMAPE:  25.503736216439687 index:  46
sMAPE:  25.827747982781712 index:  47
sMAPE:  26.181994859616548 index:  48
sMAPE:  26.549659972826927 index:  49

In [ ]:
sMAPE(np.array(y_test),np.array(y_pred_final))

21.182009662437828

In [ ]:
rate = np.array(y_pred_final) / np.array(y_test)

In [ ]:
(rate>2).astype(int).sum() / 232 * 100

3.8793103448275863